# Generated by Django 6.1.1 on 2026-09-27 04:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('QUIZ', 'کوئیز'), ('MIDTERM', 'میان\u200cترم'), ('FINAL', 'پایان\u200cترم'), ('HOMEWORK', 'تکلیف'), ('CLASS_ACTIVITY', 'فعالیت کلاسی')], default='QUIZ', max_length=20, verbose_name='نوع نمره')),
                ('term', models.CharField(choices=[('FIRST', 'نیم\u200cسال اول'), ('SECOND', 'نیم\u200cسال دوم')], default='FIRST', max_length=10, verbose_name='نیم\u200cسال')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='نمره')),
                ('max_score', models.DecimalField(decimal_places=2, default=20, max_digits=4, verbose_name='نمره کامل')),
                ('date', models.DateField(verbose_name='تاریخ ثبت')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='توضیح معلم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.studentprofile', verbose_name='دانش\u200cآموز')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.subject', verbose_name='درس')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='academics.teacherprofile', verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'نمره',
                'verbose_name_plural': 'نمرات',
                'ordering': ['-date'],
            },
        ),
    ]
