# Generated by Django 6.1.1 on 2026-09-27 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('PRESENT', 'حاضر'), ('ABSENT', 'غایب'), ('LATE', 'با تاخیر'), ('EXCUSED', 'غیبت موجه')], default='PRESENT', max_length=10, verbose_name='وضعیت')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.schoolclass', verbose_name='کلاس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.studentprofile', verbose_name='دانش\u200cآموز')),
                ('timetable_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.timetableentry', verbose_name='جلسه درسی')),
            ],
            options={
                'verbose_name': 'حضور و غیاب',
                'verbose_name_plural': 'حضور و غیاب',
                'ordering': ['-date'],
                'unique_together': {('student', 'timetable_entry', 'date')},
            },
        ),
    ]
